insert into role (id, role_name, created_at) values(1, 'CONTENT_ADMIN', now());
insert into role (id, role_name,created_at) values(2, 'CONTENT_CREATOR', now());
insert into role (id, role_name, created_at) values(3, 'CONTENT_REVIEWER', now());
insert into role (id, role_name, created_at) values(4, 'CONTENT_CREATOR', now());
insert into role (id, role_name, created_at) values(5, 'CREATIVE_ADMIN', now());
insert into role (id, role_name, created_at) values(6, 'CREATIVE_CREATOR', now());
insert into role (id, role_name, created_at) values(7, 'EXECUTIVE RECRUITER', now());
insert into role (id, role_name, created_at) values(8, 'ORG_ADMIN', now());
insert into role (id, role_name, created_at) values(9, 'PANELIST', now());
insert into role (id, role_name, created_at) values(10, 'PRESENTOR', now());
insert into role (id, role_name, created_at) values(11, 'RECRUITER', now());
insert into role (id, role_name, created_at) values(12, 'STUDENT', now());
insert into role (id, role_name, created_at) values(13, 'SUPER_ADMIN', now());
insert into role (id, role_name, created_at) values(14, 'TRAINER', now());
